<?php return array(
    'root' => array(
        'name' => 'yiisoft/yii2-app-basic',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '2891d4845894a1268a5830fcda0eb56d71fc9028',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'bower-asset/bootstrap' => array(
            'pretty_version' => 'v5.3.2',
            'version' => '5.3.2.0',
            'reference' => '344e912d04b5b6a04482113eff20ab416ff01048',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/bootstrap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/inputmask' => array(
            'pretty_version' => '3.3.11',
            'version' => '3.3.11.0',
            'reference' => '5e670ad62f50c738388d4dcec78d2888505ad77b',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/inputmask',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/jquery' => array(
            'pretty_version' => '3.6.4',
            'version' => '3.6.4.0',
            'reference' => '91ef2d8836342875f2519b5815197ea0f23613cf',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/jquery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/punycode' => array(
            'pretty_version' => 'v1.3.2',
            'version' => '1.3.2.0',
            'reference' => '38c8d3131a82567bfef18da09f7f4db68c84f8a3',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/punycode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/yii2-pjax' => array(
            'pretty_version' => '2.0.8',
            'version' => '2.0.8.0',
            'reference' => 'a9298d57da63d14a950f1b94366a864bc62264fb',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/yii2-pjax',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cebe/markdown' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '9bac5e971dd391e2802dca5400bbeacbaea9eb86',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cebe/markdown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '84a527db05647743d50373e0ec53a152f2cde568',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dragonmantank/cron-expression' => array(
            'pretty_version' => 'v1.2.1',
            'version' => '1.2.1.0',
            'reference' => '9504fa9ea681b586028adaaa0877db4aecf32bad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dragonmantank/cron-expression',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '4.0.2',
            'version' => '4.0.2.0',
            'reference' => 'ebaaf5be6c0286928352e054f2d5125608e5405e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.17.0',
            'version' => '4.17.0.0',
            'reference' => 'bbc513d79acf6691fa9cf10f192c90dd2957f18c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fakerphp/faker' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'reference' => 'e3daa170d00fde61ea7719ef47bb09bb8f1d9b01',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fakerphp/faker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'kartik-v/yii2-dialog' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => '510c3a35ffe79987cde9a9366cedbff545fd92d4',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-dialog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-grid' => array(
            'pretty_version' => 'v3.5.3',
            'version' => '3.5.3.0',
            'reference' => 'cfc1a8e18bddfe22668783abb70f08583abab0a9',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-grid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-krajee-base' => array(
            'pretty_version' => 'v3.0.5',
            'version' => '3.0.5.0',
            'reference' => '5c095126d1be47e0bb1f92779b7dc099f6feae31',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-krajee-base',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-mpdf' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '17fda1cb084c58fee6014026d35af5faf73316ef',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-mpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mpdf/mpdf' => array(
            'pretty_version' => 'v6.1.3',
            'version' => '6.1.3.0',
            'reference' => '7f138bf7508eac895ac2c13d2509b056ac7e7e97',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpdf/mpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.8.1',
            'version' => '6.8.1.0',
            'reference' => 'e88da8d679acc3824ff231fdc553565b802ac016',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpspec/php-diff' => array(
            'pretty_version' => 'v1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'fc1156187f9f6c8395886fe85ed88a0a245d72e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/php-diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'setasign/fpdi' => array(
            'pretty_version' => '1.6.2',
            'version' => '1.6.2.0',
            'reference' => 'a6ad58897a6d97cc2d2cd2adaeda343b25a368ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sharkom/yii2-cron' => array(
            'pretty_version' => 'v1.1.11',
            'version' => '1.1.11.0',
            'reference' => '761c9c861e50bb593a230d89ab12a1bb9d3eb380',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../sharkom/yii2-cron',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sharkom/yii2-cronjob-widget' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'af3513cdbe8ceeb35035a93014682e872b43a547',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../sharkom/yii2-cronjob-widget',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'shuchkin/simplexlsxgen' => array(
            'pretty_version' => '1.3.17',
            'version' => '1.3.17.0',
            'reference' => '6dcad83f09f94dd9ca9ccac05e69935727d7d7c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../shuchkin/simplexlsxgen',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.4.0',
            'version' => '3.4.0.0',
            'reference' => '7c3aff79d10325257a001fcf92d991f24fc967cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v6.3.2',
            'version' => '6.3.2.0',
            'reference' => 'adb01fe097a4ee930db9258a3cc906b5beb5cf2e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v3.4.0',
            'version' => '3.4.0.0',
            'reference' => 'a76aed96a42d2b521153fb382d418e30d18b59df',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'symfony/mailer' => array(
            'pretty_version' => 'v6.3.5',
            'version' => '6.3.5.0',
            'reference' => 'd89611a7830d51b5e118bca38e390dea92f9ea06',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v6.3.5',
            'version' => '6.3.5.0',
            'reference' => 'd5179eedf1cb2946dbd760475ebf05c251ef6a6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => 'ecaafce9f77234a6a449d29e49267ba10499116d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => '8c4ad05dd0120b6a53c1ca374dca2ad0a1c4ed92',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => '42292d99c55abe617799667f454222c54c60e229',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => '70f4aebd92afca2f865444d30a4d2151c13c3179',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => '6caa57379c4aec19c0a12a38b59b26487dcfe4b5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v5.4.28',
            'version' => '5.4.28.0',
            'reference' => '45261e1fccad1b5447a8d7a8e67aa7b4a9798b7b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.4.0',
            'version' => '3.4.0.0',
            'reference' => 'b3313c2dbffaf71c8de2934e2ea56ed2291a3838',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2' => array(
            'pretty_version' => '2.0.49.3',
            'version' => '2.0.49.3',
            'reference' => '783f65c9a743dfd7484b6026f1aa6f25e37159d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yiisoft/yii2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-app-basic' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '2891d4845894a1268a5830fcda0eb56d71fc9028',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-bootstrap5' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '0ce35f80ca07763fa2c6f38d1c0a1aaf65c76d2e',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-bootstrap5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-composer' => array(
            'pretty_version' => '2.0.10',
            'version' => '2.0.10.0',
            'reference' => '94bb3f66e779e2774f8776d6e1bdeab402940510',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../yiisoft/yii2-composer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-debug' => array(
            'pretty_version' => '2.1.25',
            'version' => '2.1.25.0',
            'reference' => '4d011b9bfc83bde71cde43c9f6837f5a74685ea7',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-debug',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-elasticsearch' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'd697c961f03dc3c9554cfa6e4836db5db00c0310',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-elasticsearch',
            'aliases' => array(
                0 => '2.1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-faker' => array(
            'pretty_version' => '2.0.5',
            'version' => '2.0.5.0',
            'reference' => '8c361657143bfaea58ff7dcc9bf51f1991a46f5d',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-faker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-gii' => array(
            'pretty_version' => '2.2.6',
            'version' => '2.2.6.0',
            'reference' => 'ac574e7e2c29fd865145c8688719f252d19aae23',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-gii',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-symfonymailer' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '82f5902551a160633c4734b5096977ce76a809d9',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-symfonymailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
